### PR TITLE
Add 'where.raw(String whereSql)'

### PR DESCRIPTION
**Pull request by debuggerx01**
With this changes, this code:
```dart
var query = EmployeeQuery()
    ..where?.firstName.equals('Rich')
    ..where?.lastName.equals('Person')
    ..where?.raw('COM.deleted = false')
    ..orWhere((w) => w.salary.greaterThanOrEqualTo(75000))
    ..join('companies', 'company_id', 'id', alias: 'COM');

  var richPerson = await query.getOne(_FakeExecutor());
```
will generate sql:
```sql
SELECT employees.id, employees.created_at, employees.updated_at, employees.first_name, employees.last_name, CAST (employees.salary AS text) FROM employees  INNER JOIN companies COM ON employees.company_id=COM.id WHERE employees.first_name = @first_name AND employees.last_name = @last_name AND  (COM.deleted = false) OR (salary >= CAST ("75000.0" as decimal)) and values: {first_name: Rich, last_name: Person}
```

### CODE REVIEW

**Comment by dukefirehawk** [comment]
Can you run `dart run build_runner build` under `angel_orm_test` folder and then run `dart test` under `angel_orm_postres` folder with your changes to see if all unit tests are ok? Would be great if can add a unit test under `angel_orm_test` for this. This will guard against code change later from breaking it.

**Comment by debuggerx01** [comment]
> Can you run `dart run build_runner build` under `angel_orm_test` folder and then run `dart test` under `angel_orm_postres` folder with your changes to see if all unit tests are ok? Would be great if can add a unit test under `angel_orm_test` for this. This will guard against code change later from breaking it.

With pleasure, I will do it later.

**Comment by debuggerx01** [comment]
> Can you run `dart run build_runner build` under `angel_orm_test` folder and then run `dart test` under `angel_orm_postres` folder with your changes to see if all unit tests are ok? Would be great if can add a unit test under `angel_orm_test` for this. This will guard against code change later from breaking it.

Hi, I added `join_test` to `angel_orm_test`, and all the tests have passed, please check~

**Comment by dukefirehawk** [comment]
@debuggerx01 Nice work. BTW I've also setup Github Action to automate these tests. Let me know if you run into any issues. Note that `dependency_overrides` was added to `pubspec.yaml` to enable automated tests to run with the local packages.

**Pull request merged**
